server:
  port: 8082
spring:
  application:
    name: ChatPlay
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatplay
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 32
          max-idle: 16
          min-idle: 8
  mail:
    host: smtp.qq.com
    port: 587
    default-encoding: UTF-8
    username: fqy.yanhuo@qq.com
    password: zactpccpcxjodjaj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  mapper-locations: classpath:com/yanhuo/chatplay/mapper/xml/*.xml

Tencent:
  DefaultUrl: https://www.fuqiuyao.xyz/
  appid: 1313823601
  accessKey: AKID73mIYZNxHK9i2b7QWQ4VvIXlhZCdqr5D
  secretKey: 1tZ9Wt56vVs1uWvCH8k5FAqWyDE2Zqsl
  regionName: ap-nanjing
  bucketName: avatar-1313823601
